### ISSUE TITLE
Add to library a method for arrays and  objects which opposite to empty

### ISSUE THREAD

**Issue by vvalgis** [LestaD/nonstandard.js#1]
With such method, it's easier to check if object isn't empty in condition expression e.g.:
`if (Object.present([1, 2, 3])) { ...`

**Comment by LestaD** [comment]
0.10.2

**Comment by sergeysova** [comment]
Relased in [nonstandard@0.10.2](https://github.com/LestaD/nonstandard.js/releases/tag/0.10.2)
